version: '3'

services:
   prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     ports:
       - 9090:9090
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
   
   grafana:
     image: grafana/grafana:latest
     container_name: grafana
     ports:
       - 3000:3000
     links:
       - prometheus

   nodes:
     image: prom/node-exporter
     container_name: node-exporter
     ports:
       - 9100:9100  
