global:
  scrape_interval: 15s
  evaluation_interval: 15s    

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
       - targets: ['localhost:9090']

   - job_name: 'node_exporter'
     static_configs:
       - targets: ['10.3.2.218:9100']
       - targets: ['10.3.2.219:9100']

#   - job_name: 'node_exporter1'
#     static_configs:
#       - targets: ['10.3.2.219:9100']
